Repository FlaschenbookProject/Flaschenbook, pull requests merged in 2023-08, with the labels that each got.

#20 Chore : add gitmessage.txt
  .gitmessage.txt
Labels: 📃 Docs

#21 feat : pep8 linting git action 작성
  .github/workflows/pep8_linting.yml
Labels: ✨ Feature, ⚙ Setting

#25 chore : 기본 개발환경 세팅
  .gitignore
  docker-compose.yml
  flaschenbook-react-app/.gitignore
  flaschenbook-react-app/Dockerfile
  flaschenbook-react-app/README.md
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/public/favicon.ico
  flaschenbook-react-app/public/index.html
  flaschenbook-react-app/public/logo192.png
  flaschenbook-react-app/public/logo512.png
  flaschenbook-react-app/public/manifest.json
  flaschenbook-react-app/public/robots.txt
  flaschenbook-react-app/src/App.css
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/App.test.js
  flaschenbook-react-app/src/index.css
  flaschenbook-react-app/src/index.js
  flaschenbook-react-app/src/logo.svg
  flaschenbook-react-app/src/reportWebVitals.js
  flaschenbook-react-app/src/setupTests.js
  flaschenbook-spring-app/.gitignore
  flaschenbook-spring-app/Dockerfile
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/gradle/wrapper/gradle-wrapper.jar
  flaschenbook-spring-app/gradle/wrapper/gradle-wrapper.properties
  flaschenbook-spring-app/gradlew
  flaschenbook-spring-app/gradlew.bat
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/java/com/example/flaschenbookspringapp/DemoApplication.java
  flaschenbook-spring-app/src/main/resources/application.properties
  flaschenbook-spring-app/src/test/java/com/example/flaschenbookspringapp/DemoApplicationTests.java
  fluentd/Dockerfile
  nginx/Dockerfile
Labels: ⚙ Setting

#26 Chore : 기초 파일구조 세팅 및 CI 추가
  .github/workflows/pep8_linting.yml
  .gitignore
  docker-compose.yml
  flaschenbook-react-app/.gitignore
  flaschenbook-react-app/Dockerfile
  flaschenbook-react-app/README.md
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/public/favicon.ico
  flaschenbook-react-app/public/index.html
  flaschenbook-react-app/public/logo192.png
  flaschenbook-react-app/public/logo512.png
  flaschenbook-react-app/public/manifest.json
  flaschenbook-react-app/public/robots.txt
  flaschenbook-react-app/src/App.css
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/App.test.js
  flaschenbook-react-app/src/index.css
  flaschenbook-react-app/src/index.js
  flaschenbook-react-app/src/logo.svg
  flaschenbook-react-app/src/reportWebVitals.js
  flaschenbook-react-app/src/setupTests.js
  flaschenbook-spring-app/.gitignore
  flaschenbook-spring-app/Dockerfile
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/gradle/wrapper/gradle-wrapper.jar
  flaschenbook-spring-app/gradle/wrapper/gradle-wrapper.properties
  flaschenbook-spring-app/gradlew
  flaschenbook-spring-app/gradlew.bat
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/java/com/example/flaschenbookspringapp/DemoApplication.java
  flaschenbook-spring-app/src/main/resources/application.properties
  flaschenbook-spring-app/src/test/java/com/example/flaschenbookspringapp/DemoApplicationTests.java
  fluentd/Dockerfile
  nginx/Dockerfile
Labels: 📃 Docs, ⚙ Setting

#29 Docs : Read Me 제목 수정
  README.md
Labels: 📃 Docs

#31 Chore: ECR에 저장할 spring boot docker image를 위한 세팅
  README.md
  flaschenbook-spring-app/.gitignore
  flaschenbook-spring-app/Dockerfile
Labels: ⚙ Setting

#30 Chore : airflow setting
  airflow/Dockerfile
  airflow/config/.gitkeep
  airflow/dags/.gitkeep
  airflow/docker-compose.yaml
  airflow/plugins/.gitkeep
  airflow/requirements.txt
  airflow/scripts/.gitkeep
Labels: ⚙ Setting

#32 Chore : etc service setting
  .gitmessage.txt
  fluentd/fluentd.conf
  nginx/Dockerfile
  nginx/nginx.conf
Labels: ⚙ Setting

#33 Chore : 개발환경 세팅
  .gitmessage.txt
  airflow/Dockerfile
  airflow/config/.gitkeep
  airflow/dags/.gitkeep
  airflow/docker-compose.yaml
  airflow/plugins/.gitkeep
  airflow/requirements.txt
  airflow/scripts/.gitkeep
  fluentd/fluentd.conf
  nginx/Dockerfile
  nginx/nginx.conf
Labels: ⚙ Setting

#35 Feat : 네이버, 카카오 API 데이터 수집 및 적재 스크립트 작성
  .gitignore
  airflow/scripts/Dockerfile
  airflow/scripts/data/aladin/.gitkeep
  airflow/scripts/data/kakao/.gitkeep
  airflow/scripts/data/naver/.gitkeep
  airflow/scripts/get_api.py
  airflow/scripts/init_get_api.py
Labels: ✨ Feature

#37 Feature : PEP8 기준으로 코드 수정
  airflow/scripts/get_api.py
  airflow/scripts/init_get_api.py
Labels: 🐞 BugFix, 🔨 Refactor

#39 chore : 79자 넘어감 rule 무시하도록 수정
  .github/workflows/pep8_linting.yml
Labels: 📃 Docs, ⚙ Setting

#41 refactor : PEP8에 맞추어 코드 리팩토링
  README.md
  airflow/scripts/get_api_library.py
  airflow/scripts/get_api_new_isbn.py
Labels: 🔨 Refactor

#42 Refactor : 코드 함수화
  airflow/scripts/init_get_api.py
Labels: 🔨 Refactor

#48 feat : file operation의 공통 함수 중 폴더 내부 파일 수 조회 함수 추가
  airflow/scripts/get_api.py
  airflow/scripts/get_api_library.py
  airflow/scripts/get_api_new_isbn.py
  airflow/scripts/init_get_api_aladin.py
  airflow/scripts/init_isbn_file_to_s3.py
  airflow/scripts/isbn_file_to_s3.py
  airflow/scripts/utils/api_operations.py
  airflow/scripts/utils/connections.py
  airflow/scripts/utils/file_operations.py
Labels: ✨ Feature

#49 Refactor : 코드 리팩토링 및 버그 수정
  .gitignore
  airflow/scripts/get_api.py
  airflow/scripts/init_get_api.py
  airflow/scripts/init_get_api_kakao.py
  airflow/scripts/utils/api_operations.py
Labels: 🐞 BugFix, 🔨 Refactor

#50 Feat : 매일 new book 데이터 사이트별 api로부터 가져오는 dag작성
  airflow/Dockerfile
  airflow/dags/base/__init__.py
  airflow/dags/base/base_dag.py
  airflow/dags/daily_fetch_new_book_data.py
  airflow/docker-compose.yaml
  airflow/requirements.txt
Labels: ✨ Feature, ⚙ Setting

#51 Refactor : utils 함수들에 타입 힌트와 주석 추가
  airflow/requirements.txt
  airflow/scripts/Dockerfile
  airflow/scripts/get_api.py
  airflow/scripts/init_get_api_kakao.py
  airflow/scripts/init_get_api_naver.py
  airflow/scripts/utils/api_operations.py
  airflow/scripts/utils/connections.py
  airflow/scripts/utils/file_operations.py
Labels: 🔨 Refactor

#52 feat : aladin init 스크립트 작성, init 실행을 위한 init.py 작성
  airflow/__init__.py
  airflow/scripts/init.py
  airflow/scripts/init/__init__.py
  airflow/scripts/init/get_api_library.py
  airflow/scripts/init/init_get_api_aladin.py
  airflow/scripts/init/init_get_api_kakao.py
  airflow/scripts/init/init_get_api_naver.py
  airflow/scripts/init/init_isbn_file_to_s3.py
Labels: ✨ Feature

#53 fix: json 오류 관련 예외 처리 로직 추가
  airflow/scripts/init/init_get_api_aladin.py
Labels: 🐞 BugFix

#54 Feat : terraform 사용하여 airflow aws infra 세팅
  .gitignore
  airflow/Dockerfile
  airflow/config/.gitkeep
  airflow/config/airflow.cfg
  airflow/config/entrypoint.sh
  airflow/infrastructure/airflow_flower.tf
  airflow/infrastructure/airflow_scheduler.tf
  airflow/infrastructure/airflow_web_server.tf
  airflow/infrastructure/airflow_web_server_lb.tf
  airflow/infrastructure/airflow_workers.tf
  airflow/infrastructure/config.tf
  airflow/infrastructure/ecs.tf
  airflow/infrastructure/ecs_services.tf
  airflow/infrastructure/network.tf
  airflow/infrastructure/output.tf
  airflow/infrastructure/postgres.tf
  airflow/infrastructure/provider.tf
  airflow/infrastructure/redis.tf
  airflow/requirements.txt
  airflow/scripts/push_to_ecr.sh
Labels: ✨ Feature, ⚙ Setting

#56 feat : spring boot 재세팅 및 PEP8에 맞춰 코드 리팩토링
  airflow/scripts/init/init_get_api_aladin.py
  airflow/scripts/isbn_file_to_s3.py
  flaschenbook-spring-app/.gitignore
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/java/com/example/flaschenbookspringapp/DemoApplication.java
  flaschenbook-spring-app/src/test/java/com/example/flaschenbookspringapp/DemoApplicationTests.java
Labels: ✨ Feature, 🔨 Refactor

#57 Refactor : pep8 기준으로 코드 수정
  airflow/scripts/get_api_new_isbn.py
  airflow/scripts/init.py
  airflow/scripts/init/get_api_library.py
  airflow/scripts/init/init_get_api_aladin.py
  airflow/scripts/isbn_file_to_s3.py
Labels: 🔨 Refactor

#58 Merge : dev to main
  .github/workflows/pep8_linting.yml
  .gitignore
  README.md
  airflow/Dockerfile
  airflow/__init__.py
  airflow/config/airflow.cfg
  airflow/config/entrypoint.sh
  airflow/dags/base/__init__.py
  airflow/dags/base/base_dag.py
  airflow/dags/daily_fetch_new_book_data.py
  airflow/docker-compose.yaml
  airflow/infrastructure/airflow_flower.tf
  airflow/infrastructure/airflow_scheduler.tf
  airflow/infrastructure/airflow_web_server.tf
  airflow/infrastructure/airflow_web_server_lb.tf
  airflow/infrastructure/airflow_workers.tf
  airflow/infrastructure/config.tf
  airflow/infrastructure/ecs.tf
  airflow/infrastructure/ecs_services.tf
  airflow/infrastructure/network.tf
  airflow/infrastructure/output.tf
  airflow/infrastructure/postgres.tf
  airflow/infrastructure/provider.tf
  airflow/infrastructure/redis.tf
  airflow/requirements.txt
  airflow/scripts/Dockerfile
  airflow/scripts/data/aladin/.gitkeep
  airflow/scripts/data/kakao/.gitkeep
  airflow/scripts/data/naver/.gitkeep
  airflow/scripts/get_api.py
  airflow/scripts/get_api_new_isbn.py
  airflow/scripts/init.py
  airflow/scripts/init/__init__.py
  airflow/scripts/init/get_api_library.py
  airflow/scripts/init/init_get_api_aladin.py
  airflow/scripts/init/init_get_api_kakao.py
  airflow/scripts/init/init_get_api_naver.py
  airflow/scripts/init/init_isbn_file_to_s3.py
  airflow/scripts/isbn_file_to_s3.py
  airflow/scripts/push_to_ecr.sh
  airflow/scripts/utils/__init__.py
  airflow/scripts/utils/api_operations.py
  airflow/scripts/utils/connections.py
  airflow/scripts/utils/file_operations.py
  flaschenbook-spring-app/.gitignore
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/java/com/example/flaschenbookspringapp/DemoApplication.java
  flaschenbook-spring-app/src/test/java/com/example/flaschenbookspringapp/DemoApplicationTests.java
Labels: ✨ Feature, 🌏 Deploy, ⚙ Setting, 🐞 BugFix, 🔨 Refactor

#60 feat : spring boot, react 개발 환경 연동
  airflow/dags/daily_get_new_book_isbn.py
  docker-compose.yml
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/src/App.js
  flaschenbook-spring-app/Dockerfile
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/java/com/book/flaschenbook/FlaschenbookApplication.java
  flaschenbook-spring-app/src/main/java/com/book/flaschenbook/TestController.java
  flaschenbook-spring-app/src/main/resources/application.properties
  flaschenbook-spring-app/src/test/java/com/book/flaschenbook/FlaschenbookApplicationTests.java
  nginx/nginx.conf
Labels: ✨ Feature, ⚙ Setting, ✅ Test, 📬 API

#63 Fix : DAG에서 사용되는 환경변수 airflow variable로 변경
  airflow/dags/daily_fetch_new_book_data.py
Labels: 🐞 BugFix

#74 Chore : local docker setting
  airflow/Dockerfile.dev
  airflow/docker-compose.yaml
  airflow/requirements.txt
  airflow/scripts/Dockerfile
Labels: ⚙ Setting, 🐞 BugFix

#78 Feat : 교보문고 리뷰데이터 웹 스크래핑 스크립트 작성
  airflow/scripts/README.md
  airflow/scripts/scrap_kyobo.py
  airflow/scripts/utils/api_operations.py
Labels: ✨ Feature, 📃 Docs, 🐞 BugFix

#79 Feat : raw -> cleaned 변환하는 lambda function 작성
  lambda/raw_to_cleaned/key_mapping.py
  lambda/raw_to_cleaned/lambda_function.py
  lambda/raw_to_cleaned/transform_data.py
Labels: ✨ Feature

#81 feature: API 배치 데이터 날짜 세팅 수정 및 s3 적재 로직 추가
  airflow/dags/daily_fetch_new_book_data.py
  airflow/dags/daily_get_new_book_isbn.py
  airflow/scripts/get_api.py
  airflow/scripts/get_api_new_isbn.py
  airflow/scripts/isbn_file_to_s3.py
Labels: ✨ Feature, 🐞 BugFix

#83 refactor :json 저장 함수 목적에 맞추어 file_operations으로 수정
  airflow/scripts/get_api_new_isbn.py
  airflow/scripts/utils/api_operations.py
  airflow/scripts/utils/file_operations.py
Labels: 🔨 Refactor

#82 Feat : cleaned to curated 변환 lambda function 추가
  lambda/cleaned_to_curated/lambda_function.py
Labels: ✨ Feature, ✅ Test

#86 Fix : 교보문고 리뷰 웹 스크래핑 스크립트 예외처리 추가
  airflow/scripts/scrap_kyobo.py
Labels: 🐞 BugFix

#88 feat : 알라딘 책 속으로, 리뷰 스크래핑 스크립트 작성
  airflow/dags/daily_fetch_new_book_data.py
  airflow/dags/daily_get_new_book_isbn.py
  airflow/dags/get_review_content_new_book.py
  airflow/scripts/init/init_get_api_aladin.py
  airflow/scripts/init/init_get_api_kakao.py
  airflow/scripts/init/init_get_api_naver.py
  airflow/scripts/scrap_aladin.py
Labels: ✨ Feature, 🔨 Refactor

#94 Feat : curated 데이터 db 적재하는 script 작성 (AWS Glue에서 사용)
  glue/load_book_detail.py
  glue/load_book_info.py
  glue/load_review.py
Labels: ✨ Feature

#96 feat : 교보 스크립트 책 속으로 추가 및 ETL DAG 작성
  airflow/dags/daily_fetch_new_book_data.py
  airflow/dags/get_review_content_new_book.py
  airflow/scripts/scrap_aladin.py
  airflow/scripts/scrap_kyobo.py
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#97 fix: 교보 책 속으로 오류 수정
  airflow/scripts/scrap_kyobo.py
Labels: 🐞 BugFix

#98 Fix : spring setting
  .gitignore
  flaschenbook-spring-app/build.gradle
  flaschenbook-spring-app/flaschenbook/.gitignore
  flaschenbook-spring-app/flaschenbook/Dockerfile
  flaschenbook-spring-app/flaschenbook/build.gradle
  flaschenbook-spring-app/flaschenbook/gradle/wrapper/gradle-wrapper.jar
  flaschenbook-spring-app/flaschenbook/gradle/wrapper/gradle-wrapper.properties
  flaschenbook-spring-app/flaschenbook/gradlew
  flaschenbook-spring-app/flaschenbook/gradlew.bat
  flaschenbook-spring-app/flaschenbook/settings.gradle
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/FlaschenbookApplication.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/TestController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookContent.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookDetail.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookDetailId.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookInfo.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookReview.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/UserInfo.java
  flaschenbook-spring-app/flaschenbook/src/main/resources/application.properties
  flaschenbook-spring-app/flaschenbook/src/test/java/com/book/flaschenbook/FlaschenbookApplicationTests.java
  flaschenbook-spring-app/settings.gradle
  flaschenbook-spring-app/src/main/resources/application.properties
Labels: ✨ Feature, ⚙ Setting

#99 fix : 파라미터 이름과 변수 이름 구분
  airflow/scripts/scrap_kyobo.py
Labels: 🐞 BugFix

#100 fix : 화면 로드 전 요소 조회해 요소를 찾지 못하는 오류 수정
  airflow/scripts/scrap_kyobo.py
Labels: 🐞 BugFix

#101 Feat : User api 개발
  flaschenbook-spring-app/flaschenbook/build.gradle
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/AppConfig.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/SecurityConfig.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/UserController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/UserEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/UserInfo.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/UserModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/UserRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/UserService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/UserServiceImpl.java
  flaschenbook-spring-app/flaschenbook/src/main/resources/application-dev.properties
  flaschenbook-spring-app/flaschenbook/src/main/resources/application-prod.properties
  flaschenbook-spring-app/flaschenbook/src/main/resources/application.properties
Labels: ✨ Feature, ⚙ Setting, 📬 API

#114 Feat : 로그아웃 기능 추가, 로그인 기능 버그 수정, 세션 데이터 관련 기능 추가
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/components/Login.js
  flaschenbook-react-app/src/components/MainLogo.js
  flaschenbook-react-app/src/components/MyPage.js
  flaschenbook-react-app/src/components/Survey.js
  flaschenbook-react-app/src/context.js
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/UserController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/LogoutRequestDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SessionDataEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SessionDataId.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/UserModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SessionDataRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/UserService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/UserServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix

#117 Style : 전역으로 header, footer 적용
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/src/App.css
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/components/Footer.js
  flaschenbook-react-app/src/components/Login.js
  flaschenbook-react-app/src/components/Register.js
  flaschenbook-react-app/src/index.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/UserEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/UserModel.java
Labels: 🎨 Html&css

#120 Feat : 회원가입 에러 수정 및 Survey와 연동, 기타 리팩토링
  flaschenbook-react-app/src/components/Login.js
  flaschenbook-react-app/src/components/MainLogo.js
  flaschenbook-react-app/src/components/Register.js
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/UserController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/UserServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix

#122 fix : 데이터 타입 오류 수정
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/BookInfoDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookDetailEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookRepository.java
Labels: 🐞 BugFix

#123 Feat : survey 화면 작업 및 기능 개발
  flaschenbook-react-app/src/components/Survey.js
  flaschenbook-react-app/src/css/Survey.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/SurveyController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/ContentPairDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/SelectedContentsDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyContentEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyDetailsEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveysEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/SurveyContentModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveyContentRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveyDetailsRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveysRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/SurveyService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/SurveyServiceImpl.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#124 Fix : Survey 화면 수정 및 로그인 관련 기능 수정
  airflow/infrastructure/config.tf
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/components/Login.js
  flaschenbook-react-app/src/components/Register.js
  flaschenbook-react-app/src/components/Survey.js
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/UserController.java
Labels: ✨ Feature, ⚙ Setting, 🐞 BugFix, 🎨 Html&css

#125 Feat : Book 관련 테이블 repository 클래스 생성
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/BookModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookContentRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookDetailRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookInfoRepository.java
Labels: ✨ Feature

#126 Feature: web development
  flaschenbook-react-app/src/components/Home.js
  flaschenbook-react-app/src/css/Logo.css
  flaschenbook-react-app/src/css/Main.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/MainController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/BookInfoDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookCategoryEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookContentEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookInfoEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookCategoryRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix, 🎨 Html&css, 📬 API

#128 Fix : survey backend
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyDetailsEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveySummaryEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/SurveyContentModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveyDetailsRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveySummaryRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveysRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/SurveyServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix

#129 Feature: 베스트셀러, 긍정 리뷰 탑10 조회 기능 추가
  flaschenbook-react-app/src/components/Home.js
  flaschenbook-react-app/src/css/Main.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/MainController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookReviewEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookServiceImpl.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API
