Repository FlaschenbookProject/Flaschenbook, pull requests merged in 2023-09, with the labels that each got.

#130 Fix : survey API 버그 수정
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyContentEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveyContentRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/SurveyServiceImpl.java
Labels: 🐞 BugFix

#132 Feature: 상세 모달 화면 Frontent, Backend 구현
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
  flaschenbook-react-app/public/IM_Hyemin-Regular.woff
  flaschenbook-react-app/public/Kakao.png
  flaschenbook-react-app/public/aladinlogo.png
  flaschenbook-react-app/public/naver.svg
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/components/BookDetail.js
  flaschenbook-react-app/src/components/BookSliderItem.js
  flaschenbook-react-app/src/components/Home.js
  flaschenbook-react-app/src/css/Detail.css
  flaschenbook-react-app/src/css/Font.css
  flaschenbook-react-app/src/css/Main.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/MainController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/dto/BookDetailDTO.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookContentEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookInfoEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/BookModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookServiceImpl.java
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#133 Feat : Mypage 워드클라우드 기능 추가
  flaschenbook-react-app/package.json
  flaschenbook-react-app/src/components/MainLogo.js
  flaschenbook-react-app/src/components/MyPage.js
  flaschenbook-react-app/src/components/WordCloud.js
  flaschenbook-react-app/src/css/Survey.css
  flaschenbook-spring-app/flaschenbook/build.gradle
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/MyPageController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/UserController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookReviewEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/NewBookCategoryEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyContentEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyContentId.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveyDetailsEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookReviewRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveyContentRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/MyPageService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/MyPageServiceImpl.java
Labels: ✨ Feature, 🐞 BugFix, 🎨 Html&css

#135 style : font 추가 및 hover 수정
  flaschenbook-react-app/public/EF_YOONY.woff
  flaschenbook-react-app/public/HS유지체.woff
  flaschenbook-react-app/public/KyoboHand.woff
  flaschenbook-react-app/public/휴먼범석체.woff
  flaschenbook-react-app/src/components/BookSliderItem.js
  flaschenbook-react-app/src/css/Main.css
Labels: 🎨 Html&css

#136 Chore : react setting
  Dockerfile
  flaschenbook-react-app/package-lock.json
  flaschenbook-react-app/package.json
Labels: ⚙ Setting

#137 feat : 대시보드를 위한 모두의 서재 페이지 추가
  flaschenbook-react-app/src/App.js
  flaschenbook-react-app/src/components/BookDashboard.js
  flaschenbook-react-app/src/components/MainLogo.js
Labels: ✨ Feature, 🎨 Html&css

#138 Fix : mypage 연관 책 리스트 불러오는 로직 수정
  flaschenbook-spring-app/flaschenbook/build.gradle
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveySummaryEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/SurveySummaryKey.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/SurveySummaryRepository.java
Labels: ⚙ Setting, 🐞 BugFix

#139 Feature: 메인 개인 추천 서비스 추가 및 상세 워드 클라우드 추가
  flaschenbook-react-app/src/components/BookDetail.js
  flaschenbook-react-app/src/components/Home.js
  flaschenbook-react-app/src/components/MyPage.js
  flaschenbook-react-app/src/components/Survey.js
  flaschenbook-react-app/src/components/WordCloud.js
  flaschenbook-react-app/src/components/WordCloudForDetail.js
  flaschenbook-react-app/src/css/Detail.css
  flaschenbook-react-app/src/css/Font.css
  flaschenbook-react-app/src/css/Main.css
  flaschenbook-react-app/src/css/Survey.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/controller/MainController.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/entity/BookReviewEntity.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/model/BookModel.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookServiceImpl.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/MyPageServiceImpl.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/ReviewService.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/ReviewServiceImpl.java
Labels: ✨ Feature, 🎨 Html&css

#140 fix : 리뷰 스크립트 DAG 오류 수정 및 S3 KeySensor 삭제
  airflow/dags/daily_fetch_new_book_data.py
  airflow/dags/daily_get_new_book_isbn.py
  airflow/dags/get_review_content_new_book.py
  airflow/scripts/Dockerfile
  airflow/scripts/scrap_aladin.py
  airflow/scripts/scrap_kyobo.py
  airflow/scripts/utils/api_operations.py
Labels: 🐞 BugFix

#141 style : 워드 클라우드 설정 수정
  flaschenbook-react-app/src/components/WordCloudForDetail.js
  flaschenbook-react-app/src/css/Detail.css
Labels: 🎨 Html&css

#142 feat : 대시보드 이미지 추가
  flaschenbook-react-app/public/1.png
  flaschenbook-react-app/public/2.png
  flaschenbook-react-app/public/3.png
  flaschenbook-react-app/public/4.png
  flaschenbook-react-app/public/flaschenbook_dashboard.jpg
  flaschenbook-react-app/src/components/BookDashboard.js
  flaschenbook-react-app/src/css/Survey.css
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/repository/BookRepository.java
  flaschenbook-spring-app/flaschenbook/src/main/java/com/book/flaschenbook/service/BookServiceImpl.java
Labels: ✨ Feature, 🎨 Html&css

#143 Docs: Readme 작성
  README.md
Labels: 📃 Docs

#144 Feat : aws scripts 백업
  airflow/scripts/transform_parquet_column.py
  glue/load_book_content.py
  glue/load_book_detail.py
  glue/load_book_info.py
  glue/load_review.py
  lambda/cleaned_to_curated/lambda_function.py
  lambda/raw_to_cleaned/lambda_function.py
  lambda/raw_to_cleaned/transform_data.py
Labels: ✨ Feature

#147 Feat : Terraform 인프라 코드 추가 (network, db, glue)
  flaschenbook-spring-app/terraform/bastion_host.tf
  flaschenbook-spring-app/terraform/glue_catalog_db.tf
  flaschenbook-spring-app/terraform/glue_connection.tf
  flaschenbook-spring-app/terraform/glue_crawler.tf
  flaschenbook-spring-app/terraform/glue_etl_job.tf
  flaschenbook-spring-app/terraform/glue_etl_job_script.tf
  flaschenbook-spring-app/terraform/glue_role.tf
  flaschenbook-spring-app/terraform/main.tf
  flaschenbook-spring-app/terraform/network.tf
  flaschenbook-spring-app/terraform/rds.tf
  flaschenbook-spring-app/terraform/vars.tf
Labels: ✨ Feature, 🌏 Deploy

#145 Update README.md
  README.md
Labels: 📃 Docs

#152 refactor : PEP8 구조에 맞추어 코드 수정
  .flake8
  airflow/dags/daily_fetch_new_book_data.py
  airflow/scripts/transform_parquet_column.py
  airflow/scripts/utils/api_operations.py
Labels: 🔨 Refactor

#153 Chore : CI/CD 세팅 변경 및 불필요한 파일 정리
  Dockerfile
  airflow/terraform/airflow_flower.tf
  airflow/terraform/airflow_scheduler.tf
  airflow/terraform/airflow_web_server.tf
  airflow/terraform/airflow_web_server_lb.tf
  airflow/terraform/airflow_workers.tf
  airflow/terraform/config.tf
  airflow/terraform/ecs.tf
  airflow/terraform/ecs_services.tf
  airflow/terraform/network.tf
  airflow/terraform/output.tf
  airflow/terraform/postgres.tf
  airflow/terraform/provider.tf
  airflow/terraform/redis.tf
  docker-compose.yml
  flaschenbook-spring-app/terraform/code_role.tf
  flaschenbook-spring-app/terraform/codebuild.tf
  flaschenbook-spring-app/terraform/codepipeline.tf
  flaschenbook-spring-app/terraform/ecs_service.tf
Labels: ✨ Feature, 🌏 Deploy, ⚙ Setting, 🐞 BugFix

#154 fix : 잘못된 명령어 수정 및 해당 의존성 삭제 (or)
  Dockerfile
  flaschenbook-react-app/package.json
Labels: 🐞 BugFix

#155 Fix : 이미지 빌드 시 resolve되지 않는 폰트 제거
  flaschenbook-react-app/src/css/Font.css
Labels: 🐞 BugFix

#156 Fix : spring app 이미지 내에서 빌드할 수 있도록 수정
  flaschenbook-spring-app/flaschenbook/.dockerignore
  flaschenbook-spring-app/flaschenbook/Dockerfile
Labels: 🌏 Deploy, 🐞 BugFix

#158 Fix : spring app Dockerfile 명령어 수정
  flaschenbook-spring-app/flaschenbook/Dockerfile
  flaschenbook-spring-app/flaschenbook/build.gradle
Labels: ⚙ Setting, 🐞 BugFix

#157 Feat : backend AWS CodePipeline 생성 트리거 git action 추가, 모니터링 관련 자원 생성
  .github/workflows/detect_changes.yml
  flaschenbook-spring-app/flaschenbook/build.gradle
  flaschenbook-spring-app/flaschenbook/src/main/resources/application-dev.properties
  flaschenbook-spring-app/terraform/codebuild.tf
  flaschenbook-spring-app/terraform/codepipeline.tf
  flaschenbook-spring-app/terraform/ecr.tf
  flaschenbook-spring-app/terraform/ecs_alb.tf
  flaschenbook-spring-app/terraform/ecs_alb_listener.tf
  flaschenbook-spring-app/terraform/ecs_alb_target_group.tf
  flaschenbook-spring-app/terraform/ecs_cloudwatch_log_group.tf
  flaschenbook-spring-app/terraform/ecs_security_group.tf
  flaschenbook-spring-app/terraform/ecs_service.tf
  flaschenbook-spring-app/terraform/ecs_task_definition.tf
  flaschenbook-spring-app/terraform/rds.tf
  flaschenbook-spring-app/terraform/s3_bucket.tf
  flaschenbook-spring-app/terraform/vars.tf
  prometheus/Dockerfile
  prometheus/prometheus.yml
Labels: ✨ Feature, 🌏 Deploy
